CREATE TABLE "CUSTOMER" (
  "ID" NUMBER(10) CONSTRAINT "PK_CUSTOMER" PRIMARY KEY,
  "NAME" VARCHAR2(1000 CHAR),
  "USERNAME" VARCHAR2(1000 CHAR),
  "EMAIL" VARCHAR2(1000 CHAR),
  "PASSWORD" VARCHAR2(1000 CHAR)
);

CREATE SEQUENCE "CUSTOMER_SEQ" NOCACHE;

CREATE TRIGGER "CUSTOMER_BI"
  BEFORE INSERT ON "CUSTOMER"
  FOR EACH ROW
BEGIN
  IF :new."ID" IS NULL THEN
    SELECT "CUSTOMER_SEQ".nextval INTO :new."ID" FROM DUAL;
  END IF;
END;;

CREATE TABLE "QUESTIONSET" (
  "ID" NUMBER(10) CONSTRAINT "PK_QUESTIONSET" PRIMARY KEY,
  "NAME" VARCHAR2(1000 CHAR),
  "CUSTOMER" NUMBER(10) NOT NULL
);

CREATE INDEX "IDX_QUESTIONSET__CUSTOMER" ON "QUESTIONSET" ("CUSTOMER");

ALTER TABLE "QUESTIONSET" ADD CONSTRAINT "FK_QUESTIONSET__CUSTOMER" FOREIGN KEY ("CUSTOMER") REFERENCES "CUSTOMER" ("ID");

CREATE SEQUENCE "QUESTIONSET_SEQ" NOCACHE;

CREATE TRIGGER "QUESTIONSET_BI"
  BEFORE INSERT ON "QUESTIONSET"
  FOR EACH ROW
BEGIN
  IF :new."ID" IS NULL THEN
    SELECT "QUESTIONSET_SEQ".nextval INTO :new."ID" FROM DUAL;
  END IF;
END;;

CREATE TABLE "QUESTION" (
  "ID" NUMBER(10) CONSTRAINT "PK_QUESTION" PRIMARY KEY,
  "QUESTION_SET" NUMBER(10) NOT NULL,
  "TEXT" VARCHAR2(1000 CHAR)
);

CREATE INDEX "IDX_QUESTION__QUESTION_SET" ON "QUESTION" ("QUESTION_SET");

ALTER TABLE "QUESTION" ADD CONSTRAINT "FK_QUESTION__QUESTION_SET" FOREIGN KEY ("QUESTION_SET") REFERENCES "QUESTIONSET" ("ID");

CREATE SEQUENCE "QUESTION_SEQ" NOCACHE;

CREATE TRIGGER "QUESTION_BI"
  BEFORE INSERT ON "QUESTION"
  FOR EACH ROW
BEGIN
  IF :new."ID" IS NULL THEN
    SELECT "QUESTION_SEQ".nextval INTO :new."ID" FROM DUAL;
  END IF;
END;;

CREATE TABLE "OPTION" (
  "ID" NUMBER(10) CONSTRAINT "PK_OPTION" PRIMARY KEY,
  "TEXT" VARCHAR2(1000 CHAR),
  "QUESTION" NUMBER(10) NOT NULL
);

CREATE INDEX "IDX_OPTION__QUESTION" ON "OPTION" ("QUESTION");

ALTER TABLE "OPTION" ADD CONSTRAINT "FK_OPTION__QUESTION" FOREIGN KEY ("QUESTION") REFERENCES "QUESTION" ("ID");

CREATE SEQUENCE "OPTION_SEQ" NOCACHE;

CREATE TRIGGER "OPTION_BI"
  BEFORE INSERT ON "OPTION"
  FOR EACH ROW
BEGIN
  IF :new."ID" IS NULL THEN
    SELECT "OPTION_SEQ".nextval INTO :new."ID" FROM DUAL;
  END IF;
END;
